services:
  # Zookeeper Service
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0  # Zookeeper image version 7.5.0 from Confluent
    ports:
      - "2181:2181"  # Exposing Zookeeper's default client port
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181  # Zookeeper client port setting
    networks:
      - default  # Connecting to the default network

  # Kafka Broker Service
  kafka:
    image: confluentinc/cp-kafka:7.5.0  # Kafka broker image version 7.5.0 from Confluent
    depends_on:
      - zookeeper  # Ensure Zookeeper starts before Kafka
    ports:
      - "9092:9092"  # Exposing Kafka's default broker port
    environment:
      KAFKA_BROKER_ID: 1  # Unique ID for this Kafka broker
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181  # Kafka connects to Zookeeper at this address
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092  # Advertise broker for client connections
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1  # Set replication factor to 1 (suitable for single broker setup)
    networks:
      - default  # Connecting to the default network

# Default network for communication between Kafka and Zookeeper
networks:
  default:
