auth:
  client_id: $GOOGLE_CLIENT_ID
  client_secret: $GOOGLE_CLIENT_SECRET
  server_metadata_url: https://accounts.google.com/.well-known/openid-configuration
  client_kwargs:
    scope: openid email profile

notifications:
  # Dummy notification for failed pipelines
  - pipeline_status:
      - failed
    channels:
      - $GMAIL_ACCOUNT
  # Dummy notification for completed or cancelled pipelines
  - pipeline_status:
      - completed
      - cancelled
    channels:
      - $MSTEAMS_WEBHOOK
